appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: zA/BHG+PcgK/Fwyyn0dHedO9x8jYUG3mrFqvlp+ZZuvwCDjiAnlg6yIz//7LKZxNf5G0iSEyBhCwL/WHoLFbMNjkxs7uq9U7lqj2l1lIpPCBlmd0VHidBBCx2sJbxIdTWKVNh/iBk99v/UK0gv2hUmdhD8adlboQI5Ay/eaP/FD4CMd4T2jOEbOTF7qMnXupQKmd0weUDHhLHlDPNMVQdVF6QBAN4wTo2pag+zF20VNurnsTZu8TQ9lPlAdynKQNEjLN0ILVA2gLfDA4o8QYD6HChlU0mOvmzJhbB4J7yN7V+0Vbj0O8EQNOV6teJndealRgII+CY6M0k07Q0YWEDIfHhLb+z2L543gSYTlQ1qXprNjKOiEr0+ufj4JSPuihK/V4WD8N1ypAyuaJaWSUwLAMUT155BylSSHrSZIbyC+xJVWzcF89CT4cOycQa6Miut6pAToODTvzKOXYjZTg0ZXqMg6QD3zUtW4MFFUxNnPIzLJnPkrw2QZuqCRKXBJebCoeC6foCc7Cd9iC/7Bky0C1f6zMr8H79b5ME/QN8Z++L8vA+SNrBaoJ5uxX1v0cN9W1X03+DFfyUdu2Wp/DN3YTMQ8y65q2RCqE65WWynUp/EWsFMnQPQP6jJshlbcD+z7Gm5tKLHdIvBtgaL34KOqaUThG7uQ6BzsLa5NPzkQ=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
